---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-redis-service
  labels:
    name: voting-app-redis-service
    author: Ramakrihna
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    name: voting-app-redis-pod
    author: Ramakrishna

...